version: "3"
services:
  site:
    command: "npm install && npm start"
    image: "node:9"
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    ports:
      - 3000:3000
      - 8080:8080
